### ISSUE TITLE
fixtures: replacing a record should always clean existing DB and OpenSearch versions

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-portal#65]
**Current behaviour**

Currently, people may get into troubles when updating an existing record if some fields that were previously there are missing in the updated record. For example, a recent update of JADE docs on QA led to: 

```console
$ cernopendata fixtures docs --mode replace -f /tmp/data/docs/jade-getting-started/jade-getting-started.json 
...
`opensearchpy.exceptions.RequestError: RequestError(400, 'strict_dynamic_mapping_exception', 'mapping set to strict, dynamic introduction of [collections] within [_doc] is not allowed')
```

**Expected behaviour**

Since we are always replacing the record in full, it would be good if `cernopendata fixtures --mode replace` always erases the existing content in both DB and OpenSearch when replaces it with the new version of the record. In this case, the old fields are removed and the above traceback should not happen even in case of adding/removing fields and other metadata schema changes.

**Notes**

Just for the record, the removal could be done on the DB level:

```python
from invenio_db import db
from invenio_records import Record

pid_type = "docid"
pid_value = "about-jade"

pid = PersistentIdentifier.get(pid_type, pid_value)
rec = Record.get_record(pid.object_uuid)
rec.delete(force=True)

db.session.delete(pid)
db.session.commit()
```

But it would still need the OpenSearch removal counterpart.

It may be better to solve this by modifying the fixtures behaviour not to update the record:

```python
    record = Record.get_record(pid.object_uuid)
    record.update(data)
```

as it is done now, but rather to replace the full content with new creation, as suggested by @psaiz:

```python
    Record.get_record(pid.object_uuid).delete()
    record = Record.create(data, id_=pid.object_uuid)
```

(Still to be tested.)

**Comment by psaiz** [comment]
All the metadata of the record being updated is deleted before the new entry is inserted. Note that the process goes record by record. It does not delete all the files first, and then insert all the records.
For instance, imagine that record 1 inserts files A and B, and record 2 inserts C and D. Once that has been inserted, if the records are modified and record 1 inserts files B, C and record 2 inserts A and D, that will fail with the above message. It will also fail if, instead of being record 1, it becomes record 11 (since record 1 would still exist in the database).

Could you please confirm that the use case that this ticket describes is not any of these scenarios?

**Comment by psaiz** [comment]
Deployed in production
